=== Narayan1006/FSD_CSE_21_2026/Class_02/employee_xml/employee.dtd
<!ELEMENT employee (empId, name, department, position, salary, email, phone, address, joinDate, status)>
<!ELEMENT empId (#PCDATA)>
<!ELEMENT name (firstName, lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (street, city, state, country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT joinDate (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== Narayan1006/FSD_CSE_21_2026/Class_02/employee_xml/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee SYSTEM "employee.dtd">

<employee>
    <empId>E001</empId>
    <name>
        <firstName>John</firstName>
        <lastName>Smith</lastName>
    </name>
    <department>Information Technology</department>
    <position>Software Engineer</position>
    <salary>75000</salary>
    <email>john.smith@company.com</email>
    <phone>+1-555-234-5678</phone>
    <address>
        <street>123 Main Street</street>
        <city>New York</city>
        <state>NY</state>
        <country>USA</country>
    </address>
    <joinDate>2024-01-15</joinDate>
    <status>Active</status>
</employee>
